### ISSUE TITLE
Methodology question: --days filtering by reported_at

### ISSUE THREAD

**Issue by mdavis332** [csirtgadgets/cif-v5#28]
Not an issue as much as a design reasoning question:

The `--days` filter seems to filter on on when the indicator was initially reported (source: https://github.com/csirtgadgets/cif-v5/blob/master/cif/http/feeds/utils.py#L33). 

Intuitively I think I would have expected `--days 3` to return any _new_ OR _updated_ indicators within the past 3 days, which seems like it would require filtering on `last_at` vs `reported_at`. Just curious on that one.

**Comment by wesyoung** [comment]
i *think* because last_at and reported_at are both updated on upsert? i forget offhand... might depend on either of the storage plugins..
